services:
  backend:
    build:
      context: ./Server
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Server:/app
      - /app/bin
      - /app/obj
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1 #
    depends_on:
      - frontend

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
