using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;
using ColumnAttribute = System.ComponentModel.DataAnnotations.Schema.ColumnAttribute;
using TableAttribute = Supabase.Postgrest.Attributes.TableAttribute;

namespace Server.App.Models
{   
    /// <summary>
    /// Represents an AI service in the system.
    /// This class maps to the "AiServices" table in the database.
    /// </summary>
    /// <remarks>
    /// The <see cref="AiService"/> class is used to model AI services, including their details such as title, description, price, image, and ratings.
    /// It inherits from <see cref="BaseModel"/> to provide common functionality for Supabase Postgrest models.
    /// </remarks>
    [Table("AiServices")]
    public class AiService : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiService"/> class.
        /// </summary>
        public AiService() { }

        /// <summary>
        /// Gets or sets the unique identifier for the AI service.
        /// </summary>
        /// <remarks>
        /// This property is the primary key for the "AiServices" table and is auto-generated by the database.
        /// </remarks>
        [PrimaryKey("Id", false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonIgnore]
        public long Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the AI service.
        /// </summary>
        [Column("Title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets a short description of the AI service.
        /// </summary>
        [Column("Description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the full description of the AI service.
        /// </summary>
        [Column("FullDescription")]
        public string FullDescription { get; set; }

        /// <summary>
        /// Gets or sets the price of the AI service.
        /// </summary>
        [Column("Price")]
        public string Price { get; set; }

        /// <summary>
        /// Gets or sets the image path for the AI service.
        /// </summary>
        [Column("Image")]
        public string Image { get; set; }

        /// <summary>
        /// Gets or sets the average star rating of the AI service.
        /// </summary>
        [Column("Stars")]
        public double Stars { get; set; }

        /// <summary>
        /// Gets or sets the number of reviews for the AI service.
        /// </summary>
        [Column("Reviews")]
        public int Reviews { get; set; }

        /// <summary>
        /// Gets or sets the status of the AI service (e.g., Verfied, Pending).
        /// </summary>
        [Column("Status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets the URL of the AI service.
        /// </summary>
        [Column("ServiceURL")]
        public string ServiceURL { get; set; }

        /// <summary>
        /// Gets or sets the creation date and time of the AI service.
        /// </summary>
        [Column("CreatedAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the creator of the AI service.
        /// </summary>
        [Column("CreatorId")]
        public long CreatorId { get; set; }
    }
}