using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;
using ColumnAttribute = System.ComponentModel.DataAnnotations.Schema.ColumnAttribute;
using TableAttribute = Supabase.Postgrest.Attributes.TableAttribute;

namespace Server.App.Models
{

    /// <summary>
    /// Represents the relationship between AI services and categories in the system.
    /// This class maps to the "AiServicesCategories" table in the database.
    /// </summary>
    /// <remarks>
    /// The <see cref="AiServicesCategories"/> class is used to model the many-to-many relationship
    /// between AI services and categories. It inherits from <see cref="BaseModel"/> to provide
    /// common functionality for Supabase Postgrest models.
    /// </remarks>
    [Table("AiServicesCategories")]
    public class AiServicesCategories : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiServicesCategories"/> class.
        /// </summary>
        public AiServicesCategories() { }

        /// <summary>
        /// Gets or sets the unique identifier for the relationship.
        /// </summary>
        /// <remarks>
        /// This property is the primary key for the "AiServicesCategories" table and is auto-generated by the database.
        /// </remarks>
        [PrimaryKey("Id", false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonIgnore]
        public long Id { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the AI service associated with this relationship.
        /// </summary>
        [Column("AiServiceId")]
        public long AiServiceId { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the category associated with this relationship.
        /// </summary>
        [Column("CategoryId")]
        public long CategoryId { get; set; }

    }
}