using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;
using ColumnAttribute = System.ComponentModel.DataAnnotations.Schema.ColumnAttribute;
using TableAttribute = Supabase.Postgrest.Attributes.TableAttribute;

namespace Server.App.Models
{   
    /// <summary>
    /// Represents a category in the system.
    /// This class maps to the "Categories" table in the database.
    /// </summary>
    /// <remarks>
    /// The <see cref="Category"/> class is used to model categories, which can be associated with AI services.
    /// It inherits from <see cref="BaseModel"/> to provide common functionality for Supabase Postgrest models.
    /// </remarks>
    [Table("Categories")]
    public class Category : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Category"/> class.
        /// </summary>
        public Category() { }

        /// <summary>
        /// Gets or sets the unique identifier for the category.
        /// </summary>
        /// <remarks>
        /// This property is the primary key for the "Categories" table and is auto-generated by the database.
        /// </remarks>
        [PrimaryKey("Id", false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonIgnore]
        public long Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the category.
        /// </summary>
        [Column("Name")]
        public string Name { get; set; }

    }
}