using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;
using ColumnAttribute = System.ComponentModel.DataAnnotations.Schema.ColumnAttribute;
using TableAttribute = Supabase.Postgrest.Attributes.TableAttribute;

namespace Server.App.Models {

    /// <summary>
    /// Represents a review submitted by a user for an AI service.
    /// This class maps to the "Reviews" table in the database.
    /// </summary>
    /// <remarks>
    /// The <see cref="Review"/> class is used to model user reviews for AI services. It includes properties
    /// such as the review comment, star rating, and metadata like creation date and likes/dislikes.
    /// It inherits from <see cref="BaseModel"/> to provide common functionality for Supabase Postgrest models.
    /// </remarks>
    [Table("Reviews")]
    public class Review: BaseModel {
        
        /// <summary>
        /// Initializes a new instance of the <see cref="Review"/> class.
        /// </summary>
        public Review(){}

        /// <summary>
        /// Gets or sets the unique identifier for the review.
        /// </summary>
        /// <remarks>
        /// This property is the primary key for the "Reviews" table and is auto-generated by the database.
        /// It is marked with <see cref="JsonIgnore"/> to exclude it from JSON serialization.
        /// </remarks>
        [PrimaryKey("Id",false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonIgnore]
        public long Id { get; set; } 

        /// <summary>
        /// Gets or sets the comment or text content of the review.
        /// </summary>
        [Column("CommentValue")]
        public string CommentValue { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the user who submitted the review.
        /// </summary>
        [Column("UserId")]
        public long UserId { get; set; }

        /// <summary>
        /// Gets or sets the star rating given by the user in the review.
        /// </summary>
        [Column("Stars")]
        public double Stars { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the AI service being reviewed.
        /// </summary>
        [Column("AiServiceId")]
        public long AiServiceId { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the review was created.
        /// </summary>
        [Column("CreatedAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets the number of likes received by the review.
        /// </summary>
        [Column("Likes")]
        public int Likes { get; set; }

        /// <summary>
        /// Gets or sets the number of dislikes received by the review.
        /// </summary>
        [Column("Dislikes")]
        public int Dislikes { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the review has replies.
        /// </summary>
        [Column("HasReplies")]
        public bool HasReplies { get; set; }



    }
}